### PR TITLE
Fix import section parsing to accommodate new format found in pulumi-aws

### LINKED ISSUE #1344: Import section of AWS Classic resources is broken - showing TF import statements
### What happened?

If you go to https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificate/#import you'll see something like the following:

image

### Expected Behavior

Should see the Pulumi import information

### Steps to reproduce

Go to https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificate/#import

### Output of `pulumi about`

n/a

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #1344 

On 5.42.0 we used to render Import section of the docstring for aws:acm/certificate:Certificate in the schema like this:

    ## Import

    Certificates can be imported using their ARN, e.g.,
    
    ```sh
     $ pulumi import aws:acm/certificate:Certificate cert arn:aws:acm:eu-central-1:123456789012:certificate/7e7a28d2-163f-4b8f-b9cd-822f96c08d6a
    ```

On 6.0.2 it rendered like this:

    ## Import

    terraform import {

     to = aws_acm_certificate.cert

     id = "arn:aws:acm:eu-central-1:123456789012:certificate/7e7a28d2-163f-4b8f-b9cd-822f96c08d6a" } Using `pulumi import`, import certificates using their ARN. For exampleconsole % pulumi import aws_acm_certificate.cert arn:aws:acm:eu-central-1:123456789012:certificate/7e7a28d2-163f-4b8f-b9cd-822f96c08d6a

With the changes in the PR it now renders like this:

    ## Import

    Using `pulumi import`, import certificates using their ARN. For example:

    ```sh
     $ pulumi import aws:acm/certificate:Certificate cert arn:aws:acm:eu-central-1:123456789012:certificate/7e7a28d2-163f-4b8f-b9cd-822f96c08d6a
    ```

An assert is added to panic at tfgen time if the generated import section contains the word `erraform`. 

I've rebuild pulumi-aws against these changes and verified that every AWS example passed through the new codepath and the assert above does not trigger.

### CODE REVIEW

File: pkg/tfgen/docs.go [hunk 1]
```diff
@@ -1049,6 +1050,17 @@ func parseAttributesReferenceSection(subsection []string, ret *entityDocs) {
 }
 
 func (p *tfMarkdownParser) parseImports(subsection []string) {
+	var token string
+	if p.info != nil && p.info.GetTok() != "" {
+		token = p.info.GetTok().String()
+	}
+	defer func() {
+		contract.Assertf(!strings.Contains(p.ret.Import, "erraform"),
```
Comment (t0yv0) [inline pkg/tfgen/docs.go:1058]: OK this turns out to be too strict for random and azure-ad downstream checks. Need to reconsider or downgrade to a warning... possibly some data cleanup for us to do on these.

Comment (iwahbe) [reply pkg/tfgen/docs.go:1058]: Warnings in docsgen are almost completely useless on large providers. If an import section (post processing) still contains the word "erraform", can we just drop the import section completely.

We can also add a warning, but I don't think it will change our behavior.

File: pkg/tfgen/docs.go [hunk 2]
```diff
@@ -1129,6 +1146,111 @@ func (p *tfMarkdownParser) parseImports(subsection []string) {
...
+// Recognize import example codeblocks.
+//
+// I.E, given:
+//
+//	s := "% pulumi import aws_accessanalyzer_analyzer.example example"
+//
+// Returns this:
+//
+//	parseImportCode(s) == (true, "aws_accessanalyzer_analyzer", "example", "example")
+func parseImportCode(code string) (bool, string, string, string) {
```
Comment (iwahbe) [inline pkg/tfgen/docs.go:1242]: It's really difficult to understand what we are returning here. Can we add an annotation? Also, if the first `bool` is found, I think idiomatic go has it at the end.
```suggestion
func parseImportCode(code string) (token string, ??? string, ??? string, found bool) {
```

File: pkg/tfgen/docs.go (hunk 1 above)
Comment (t0yv0) [reply pkg/tfgen/docs.go:1058]: Well, what can we do to change that? I'll add a note to ideation.

File: pkg/tfgen/docs.go (hunk 2 above)
Comment (t0yv0) [reply pkg/tfgen/docs.go]: Yup, fixed up.

**Review by iwahbe — APPROVED** [review]
2 comments, but after that LGTM!

File: pkg/tfgen/docs.go [hunk 3]
```diff
@@ -1129,6 +1151,117 @@ func (p *tfMarkdownParser) parseImports(subsection []string) {
...
+	return out.String(), true
+}
+
+func emitImportCodeBlock(w io.Writer, typeToken, name, id string) {
+	fmt.Fprintf(w, "```sh<break>\n")
+	fmt.Fprintf(w, "$ pulumi import %s %s %s\n", typeToken, name, id)
+	fmt.Fprintf(w, "<break>```<break>\n")
+}
+
+var importCodePattern = regexp.MustCompile(
```
Comment (thomas11) [inline pkg/tfgen/docs.go:1227]: It's a good practice to comment such long regexes with an example string they match.

File: pkg/tfgen/docs.go [hunk 4]
```diff
@@ -1129,6 +1151,117 @@ func (p *tfMarkdownParser) parseImports(subsection []string) {
...
+}, bool) {
+	type ret struct {
+		Name string
+		ID   string
+	}
+	if importCodePattern.MatchString(code) {
+		matches := importCodePattern.FindStringSubmatch(code)
+		return ret{Name: matches[2], ID: matches[3]}, true
+	}
+	if importCodePattern2.MatchString(code) {
```
Comment (thomas11) [inline pkg/tfgen/docs.go:1258]: This may be a bit paranoid, but when pattern 2 matches we don't actually know that it was due to accidentally repeated tokens. The additional string could be different from the matched one.

**Review by thomas11 — APPROVED** [review]

**Comment by t0yv0** [comment]
Well ok if we all don't like importCodePattern2 I can drop handling that one resource to pulumi-aws https://github.com/pulumi/pulumi-aws/issues/2760

File: pkg/tfgen/docs.go (hunk 3 above)
Comment (t0yv0) [reply pkg/tfgen/docs.go]: Done.

File: pkg/tfgen/docs.go (hunk 4 above)
Comment (t0yv0) [reply pkg/tfgen/docs.go]: moved it to https://github.com/pulumi/pulumi-aws/issues/2760

File: pkg/tfgen/docs.go [hunk 5]
```diff
@@ -1129,6 +1151,117 @@ func (p *tfMarkdownParser) parseImports(subsection []string) {
...
+}
+
+var importCodePattern = regexp.MustCompile(
+	`^[%$] (?:pulumi|terraform) import` +
+		`[\\\s]+([^.]+)[.]([^\s]+)[\\\s]+([^\s]+)\s*$`)
+
+// Data correction: ignore the first of two acidentally repeated tokens such as:
+//
+//	% pulumi import aws_n_policy.example aws_n_policy.example id
+var importCodePattern2 = regexp.MustCompile(
```
[the remark this answers is not in the document]
Comment (t0yv0) [reply pkg/tfgen/docs.go]: https://github.com/pulumi/pulumi-aws/issues/2760

File: pkg/tfgen/docs_test.go [hunk 6]
```diff
@@ -1080,3 +1120,31 @@ func (r *mockResource) GetDocs() *tfbridge.DocInfo {
 func (r *mockResource) GetTok() tokens.Token {
 	return r.token
 }
+
+func readfile(t *testing.T, file string) string {
```
[the remark this answers is not in the document]
Comment (t0yv0) [reply pkg/tfgen/docs_test.go:1119]: Ignoring windows tests for now.
