### PR TITLE
fix: Support ListTypable and SetTypable elem values for handling custom types

### LINKED ISSUE #2020: error working with terraform framework custom schema type implementing `basetypes.ListValuable`
### What happened?

- Error message: `error: Failed to prepare a resource encoder: cannot derive an encoder for resource "equinix_metal_connection": Cannot derive an encoder for property "ports": issue deriving an object encoder: Cannot derive an encoder for property "virtual_circuit_ids": when deriving converters for an element of a collection: LookupSchemaPath failed at walk.NewSchemaPath(): walk.ElementStep{} is not applicable`

- schema definition of the attribute failing:
https://github.com/equinix/pulumi-equinix/blob/a9d8f324dfa6fabbbb92d017d4ef8dcf677ef3bb/provider/cmd/pulumi-resource-equinix/schema.json#L7350-L7355

- Terraform schema:
https://github.com/equinix/terraform-provider-equinix/blob/1ef2417122f8c92b09d8d36c10e3e8473322f11b/internal/resources/metal/connection/models.go#L73

- linked issue https://github.com/equinix/pulumi-equinix/issues/94

### Example

-

### Output of `pulumi about`

-

### Additional context

This is a special case, in the Equinix terraform provider we are migrating from sdkv2 to framework, using tf5muxserver. Due to some limitations with protocol 5, we define the [`ports`](https://github.com/equinix/terraform-provider-equinix/blob/1ef2417122f8c92b09d8d36c10e3e8473322f11b/internal/resources/metal/connection/resource_schema.go#L180-L188) field with CustomType, which is a list of objects of type [`PortModel`](https://github.com/equinix/terraform-provider-equinix/blob/1ef2417122f8c92b09d8d36c10e3e8473322f11b/internal/resources/metal/connection/models.go#L66-L74). As the object is not a schema, the type of the subfields is not defined and therefore types.List cannot be used for the virtual_circuit_ids subfield and it needs a typed list, that is why we use a [ custom list of strings that implements ListValuable](https://github.com/equinix/terraform-provider-equinix/blob/1ef2417122f8c92b09d8d36c10e3e8473322f11b/internal/framework/types/listof.go#L19C29-L19C40)

- I have been able to verify that the AWS provider also fails in resources that use the same approach, for example

https://github.com/hashicorp/terraform-provider-aws/blob/eae23a82dc115e5abddba32f9de79a8899909f38/internal/service/bedrockagent/agent.go#L124

https://github.com/hashicorp/terraform-provider-aws/blob/eae23a82dc115e5abddba32f9de79a8899909f38/internal/service/bedrockagent/agent.go#L564

image

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by guineveresaenger**
Fixes #2020.

### CODE REVIEW

File: pf/tests/provider_nested_custom_types_test.go [hunk 1]
```diff
@@ -0,0 +1,290 @@
+package tfbridgetests
```
Comment (iwahbe) [inline pf/tests/provider_nested_custom_types_test.go:1]: Is there a reason why this isn't in `pf/internal/schemashim/`, similar to `custom_object_type_test.go`? I would move it there for consistency.

**Review by iwahbe — APPROVED** [review]

File: pf/tests/provider_nested_custom_types_test.go (hunk 1 above)
Comment (guineveresaenger) [reply pf/tests/provider_nested_custom_types_test.go:1]: I'm all for consistency - must've gotten lost in the mess. 👍

Comment (guineveresaenger) [reply pf/tests/provider_nested_custom_types_test.go:1]: Oh I remember now. The test provider is unavailable in `pf/internal` That's why. :/ I had it there first.

**Review by t0yv0 — APPROVED** [review]
