### PR TITLE
Fix automatic aliasing of muxed providers

### LINKED ISSUE #1937: Failures in automatic aliasing for muxed providers
### What happened?

In the case of AWS new resources are developed with Plugin Framework, and AWS is in Pulumi is a muxed provider with an
SDKv2 base and a PF based overload. Unfortunately the auto-aliasing feature does not work as expected.

Specifically, introducing a "bedrockanalysis" module to move some resource tokens for best UX has failed AWS builds with
the following message:

```
error: failed to compute dispatch for muxed provider: Resources without backing provider:
  - aws_bedrockagent_agent_knowledge_base_association_legacy
  - aws_bedrockagent_agent_alias_legacy
  - aws_bedrockagent_agent_action_group_legacy
  - aws_bedrockagent_agent_legacy
  - aws_bedrockagent_knowledge_base_legacy
  make: *** [tfgen_no_deps
```

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #1937

This PR fixes the automatic aliasing of muxed providers by dispatching a ResourceMap Clone operation to the sub-map that owns the key being cloned and making PF resource maps mutable.

### CODE REVIEW

**Comment by t0yv0** [comment]
This needs unit tests on union.go and some high-level test for the feature, but wanted to get feedback first if approach makes sense? This would need a new release of muxer and bridge.

File: pf/internal/muxer/union.go [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+		if value == nil {
+			panic("GAH2! nil resource in extension")
+		}
+		return each(key, value)
+	})
+}
+
+func (m *unionResourceMap) Set(key string, value shim.Resource) {
+	if value == nil {
+		panic("GAH! nil in Set")
```
Comment (t0yv0) [inline pf/internal/muxer/union.go:97]: Remove debugging helpers.

File: pkg/tfshim/shim.go [hunk 2]
```diff
@@ -188,6 +188,20 @@ type ResourceMap interface {
...
 
+type ResourceMapWithClone interface {
+	ResourceMap
+	Clone(oldKey, newKey string) error
+}
+
+func CloneResource(rm ResourceMap, oldKey string, newKey string) {
+	switch rm := rm.(type) {
+	case ResourceMapWithClone:
+		rm.Clone(oldKey, newKey)
```
Comment (t0yv0) [inline pkg/tfshim/shim.go:199]: Check and return an error.

**Comment by VenelinMartinov** [comment]
Looks sensible, is the main issue that previously the aliases were not added to the list of resources/data maps?

Also now that they are added, wouldn't Len return an invalid value? Do we need it to return the number of unique resources/data maps?

**Comment by t0yv0** [comment]
Hm, I can double check `Len()` impl but the intent was to keep it consistent with what you would expect.

The problem here is that we merge two maps and then we mutate the merged map, and further we try to find the owner of the resource via the said merged map. Prior to the change the _legacy resources couldn't be correlated to the owning provider. 

Hm, perhaps instead of fixing it in this way we can just teach the dispatch table builder to recognize that foo_legacy is owned by the same provider that owns foo unless there is evidence of another owner.

File: pf/internal/muxer/union.go [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+	}
+	// Sending edits to the owner map.
+	_, b := m.baseline.GetOk(key)
+	_, e := m.extension.GetOk(key)
+	switch {
+	case b && e:
+		// In the case of conflict, send the edit to both.
+		m.baseline.Set(key, value)
+		m.extension.Set(key, value)
```
Comment (iwahbe) [inline pf/internal/muxer/union.go:106]: Do we need this functionality? It is impossible to observe `m.extension.Get(key)` given `b` via this `m`, so this is useful only when we are counting on the extension used when creating `m` to be observed.

If we don't have scenarios where this happens, it feels like we should panic here to avoid the ambiguity.

**Review by iwahbe — COMMENTED** [review]
I'm having trouble understanding why we need `Clone` (instead of just `Set(key, Get(key))`). It looks like `Clone` is different from get + set only when you need to copy a key in both `baseline` and `extension` to a different value. I'm struggling to come up with a scenario where that distinction can be witnessed, since `m.Get`, `m.Range`, `m.GetOk` will only ever return the result from `m.baseline` given a conflicting key.

File: pf/internal/muxer/union.go (hunk 3 above)
Comment (t0yv0) [reply pf/internal/muxer/union.go:106]: That's fair. Was speculating without a use case here.

**Comment by t0yv0** [comment]
PTAL, added some tests around this.

**Review by iwahbe — APPROVED** [review]
Looks good to me. Lets get this merged.

I am at this point unsure what LGTM actually stands for, but anyway...
