### PR TITLE
Enforce Bijection between `PulumiToTerraformName` and `TerraformToPulumiNameV2`

### LINKED ISSUE #778: Pulumi name "base32StringSeed" incorrectly translates back to Terraform as "base32_string_seed"
### What happened?

There is an issue with translating property names that contain numbers, these property names do not turn around between Pulumi and Terraform. Attempting to use resource with such property names will result in run-time error.

Since v3.39.1 this is detected at build time as a warning. For example, running pulumi-aws gives:

```
warning: Naming error in Terraform Resource "aws_iam_virtual_mfa_device" attribute "base_32_string_seed": Pulumi name "base32StringSeed" incorrectly translates back to Terraform as "base32_string_seed"
warning: Naming error in Terraform Resource "aws_dms_s3_endpoint" attribute "rfc_4180": Pulumi name "rfc4180" incorrectly translates back to Terraform as "rfc4180"
```

It appears that this issue can be solved in pulumi-terraform-bridge itself.

### Expected Behavior

Properties such as base32_string_seed work as expected.

### Steps to reproduce

Run `make tfgen` on `pulumi-aws` against the v3.39.1 version of the bridge.

### Output of `pulumi about`

N/A

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #778

This PR adds `TerraformToPulumiNameV2`: A version of `TerraformToPulumiName` that captures the same amount of information as `PulumiToTerraformName`. 

This allows us ensure `TerraformToPulumiNameV2(PulumiToTerraformName(tfName)) == tfName` whenever possible[^1].

[^1]: The user can override this information. If there are manual overrides that conflict, we can't ensure the bijection.

### CODE REVIEW

File: pkg/tfbridge/names.go [hunk 1]
```diff
@@ -82,25 +77,60 @@ func isPulumiMaxItemsOne(ps *SchemaInfo) bool {
...
-			//			contract.Assertf(
-			//				inflector.Pluralize(name) == name || inflector.Singularize(inflector.Pluralize(name)) == name,
-			//				"expected to be able to safely pluralize name: %s (%s, %s)", name, inflector.Pluralize(name),
-			//				inflector.Singularize(inflector.Pluralize(name)))
-
-			name = pluralized
+	if sch != nil && !isPulumiMaxItemsOne(psInfo) && checkTfMaxItems(sch.Get(name), false) {
+		candidate := inflector.Pluralize(name)
+
+		var conflict bool
```
Comment (t0yv0) [inline pkg/tfbridge/names.go:120]: Aha so this refuses to pluralize on conflict. Good!

File: pkg/tfbridge/names.go [hunk 2]
```diff
@@ -82,25 +77,60 @@ func isPulumiMaxItemsOne(ps *SchemaInfo) bool {
...
 	var result string
 	var nextCap bool
 	var prev rune
 
+	var psInfo *SchemaInfo
+	if ps != nil {
+		psInfo = ps[name]
+	}
+
+	if psInfo != nil {
```
Comment (t0yv0) [inline pkg/tfbridge/names.go:110]: This now respects psInfo.Name. Good!

File: pkg/tfbridge/names.go [hunk 3]
```diff
@@ -23,12 +23,29 @@ import (
...
 
 	shim "github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim"
+	"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/schema"
 )
 
 // PulumiToTerraformName performs a standard transformation on the given name string, from Pulumi's PascalCasing or
 // camelCasing, to Terraform's underscore_casing.
 func PulumiToTerraformName(name string, tfs shim.SchemaMap, ps map[string]*SchemaInfo) string {
 	var result string
+	// First, check if any tf name points to this one.
```
Comment (t0yv0) [inline pkg/tfbridge/names.go:33]: Good, tables FTW.

File: pkg/tfbridge/names_test.go [hunk 4]
```diff
@@ -210,6 +200,41 @@ func TestBijectiveNameConversion(t *testing.T) {
...
+					Name: "plural",
+				},
+			},
+			expected: map[string]string{
+				"singular": "singular_property",
+				"plural":   "plural_property",
+			},
+		},
+		{ // Check number mapping
+			schema: map[string]*schemav2.Schema{
```
Comment (t0yv0) [inline pkg/tfbridge/names_test.go:227]: Nice.

File: pkg/tfgen/generate.go [hunk 5]
```diff
@@ -1483,18 +1486,19 @@ func input(sch shim.Schema, info *tfbridge.SchemaInfo) bool {
 //
 //	would need to understand how to unmarshal names in a language-idiomatic way (and specifically reverse the
 //	name transformation process).  This isn't impossible, but certainly complicates matters.
-func propertyName(key string, sch shim.Schema, custom *tfbridge.SchemaInfo) string {
+func propertyName(key string, sch shim.SchemaMap, custom map[string]*tfbridge.SchemaInfo) string {
 	// Use the name override, if one exists, or use the standard name mangling otherwise.
 	if custom != nil {
-		if custom.Name != "" {
-			return custom.Name
+		v := custom[key]
```
Comment (t0yv0) [inline pkg/tfgen/generate.go:1492]: Oof. Is this blocks till needed? The TerraformToPulumiNameV2 bit takes care of SchemaInfo.Name now, no? Or is the worry about the `// BUGBUG` effects ?

File: pkg/tfgen/generate.go [hunk 6]
```diff
@@ -1546,9 +1560,12 @@ func resourceName(provider string, rawname string,
...
 	if info == nil || info.Tok == "" {
 		// default transformations.
-		name := withoutPackageName(provider, rawname)                  // strip off the pkg prefix.
-		camel := tfbridge.TerraformToPulumiName(name, nil, nil, false) // camelCase the module name.
-		pascal := tfbridge.TerraformToPulumiName(name, nil, nil, true) // PascalCase the resource name.
+		name := withoutPackageName(provider, rawname)              // strip off the pkg prefix.
+		camel := tfbridge.TerraformToPulumiNameV2(name, nil, nil)  // camelCase the module name.
+		pascal := tfbridge.TerraformToPulumiNameV2(name, nil, nil) // PascalCase the resource name.
+		if pascal != "" {
+			pascal = string(unicode.ToUpper(rune(pascal[0]))) + pascal[1:]
```
Comment (t0yv0) [inline pkg/tfgen/generate.go:1567]: What's this change doing here? This feels unexpected?

**Comment by t0yv0** [comment]
There's remaining code that has not migrated to the new version. This seems dangerous to me? Or are we sure all those use cases are benign?

```
t0yv0@Antons-MacBook-Pro> git grep TerraformToPulumiName | grep -v V2 | grep -v test                                                                                                          ~/code/pulumi-terraform-bridge
pkg/tfbridge/names.go:// TerraformToPulumiName performs a standard transformation on the given name
pkg/tfbridge/names.go:func TerraformToPulumiName(name string, sch shim.Schema, ps *SchemaInfo, upper bool) string {
pkg/tfbridge/provider.go:       return TerraformToPulumiName(name, nil, nil, false),
pkg/tfbridge/provider.go:               TerraformToPulumiName(name, nil, nil, true)
pkg/tfbridge/provider.go:                       name := TerraformToPulumiName(key, meta, nil, false)
pkg/tfbridge/provider.go:                       name := TerraformToPulumiName(parts[1], schema, info, false)
pkg/tfbridge/provider.go:                       name := TerraformToPulumiName(selector.Name, schema, info, true)
pkg/tfbridge/schema.go:                 name = TerraformToPulumiName(key, getSchema(tfs, key), ps[key], false)
```

**Comment by t0yv0** [comment]
Thinking about the API a little bit.

Current API:

```
func TerraformToPulumiNameV2(name string, sch shim.SchemaMap, ps map[string]*SchemaInfo) string
func PulumiToTerraformName(name string, tfs shim.SchemaMap, ps map[string]*SchemaInfo) string
```

Suggested API:

```
type NameContext interface {
   TerraformToPulumiName(name string) string
   PulumiToTerraformName(name string) string
}
func NewNameContext(shim.SchemaMap, map[string]*SchemaInfo) NameContext
```

Having NameContext spelled out can help us refacoring this further to lift NewNameContext out of loops to avoid
quadratics. For starters we can just search/replace to `NewNameContext(schemaMap, infos).TerraformToPulumiName(n)`.

I am also wondering if this should really be this? Some callsites don't need invented names that don't exist
in the tables.

```
type NameContext interface {
   TerraformToPulumiName(name string) (string, error)
   PulumiToTerraformName(name string) (string, error)
}
```

Or perhaps:

```
type NameContext interface {
   TerraformToPulumiName(name string) string
   PulumiToTerraformName(name string) string
   KnownTerraformToPulumiName(name string) (string, error)
   KnownPulumiToTerraformName(name string) (string, error)
}
```

**Comment by t0yv0** [comment]
This fixes https://github.com/pulumi/pulumi-terraform-bridge/issues/778 I think?

File: pkg/tfbridge/names.go [hunk 7]
```diff
@@ -82,25 +77,60 @@ func isPulumiMaxItemsOne(ps *SchemaInfo) bool {
...
-	if !isPulumiMaxItemsOne(ps) && checkTfMaxItems(sch, false) {
-		pluralized := inflector.Pluralize(name)
-		if inflector.Singularize(pluralized) == name {
-			//			contract.Assertf(
-			//				inflector.Pluralize(name) == name || inflector.Singularize(inflector.Pluralize(name)) == name,
-			//				"expected to be able to safely pluralize name: %s (%s, %s)", name, inflector.Pluralize(name),
-			//				inflector.Singularize(inflector.Pluralize(name)))
-
-			name = pluralized
+	if sch != nil && !isPulumiMaxItemsOne(psInfo) && checkTfMaxItems(sch.Get(name), false) {
```
[the remark this answers is not in the document]
Comment (iwahbe) [reply pkg/tfbridge/names.go:117]: Good catch. It now reads:
```go
sch != nil && !isPulumiMaxItemsOne(psInfo) && isTfPlural(sch.Get(name))
```

File: pkg/tfgen/generate.go (hunk 5 above)
Comment (iwahbe) [reply pkg/tfgen/generate.go:1492]: That block can be yanked. The `// BUGBUG` only effects the key, which is not used in `.Name` override lookup.

File: pkg/tfgen/generate.go (hunk 6 above)
Comment (iwahbe) [reply pkg/tfgen/generate.go:1559]: Previously, the code looked like this:
https://github.com/pulumi/pulumi-terraform-bridge/blob/59a7281edaa87aa3e7c3d8544521d9d4232c05e3/pkg/tfgen/generate.go#L1550-L1551

Since `tfbrige.TerraformToPulumiName` doesn't support a (non-reversible) PascalCase option anymore, it needed to be manually reimplemented.

**Comment by iwahbe** [comment]
@t0yv0 It looks like the number of resource properties caps out at 70 (aws), with other T1 providers less then that[^1]. The performance of `PulumiToTerraformName` and `TerraformToPulumiName` are both `O(n)`. Can you point me to the hot loops where you predict this will be a problem?

I think that the API you are suggesting will give performance wins, but I'm not sure they will be noticeable. I don't think we need an API that supports known and unknown variants. Given the same schema and info maps, all operations will be reversible.

[^1]: `jq '.resources[].properties | length' provider/cmd/pulumi-resource-aws/schema.json  | sort -n | tail -10`

File: pkg/tfgen/generate.go (hunk 6 above)
Comment (t0yv0) [reply pkg/tfgen/generate.go:1559]: Got it. That makes sense.

**Comment by t0yv0** [comment]
Regardless of whether we actually optimize it or not here I have ever so slight preference for something like NameContext (though hard to find a name for it..) as it can be more obvious to document a constraint on these two functions together that they need to be invertible. Also it incidentally solves the TerraformToPulumiNameV2 wrinkle. With TerraformToPulumiNameV2 we don't have a way to ever get rid of "V2" even if we remove the original version. Would be nice to shoot for something that becomes clean down the line. Any other ideas to avoid the wrinkle?

The rest is non-binding.

#### perf

N=375 on object types.

```
$ jq '.types[].properties | length' provider/cmd/pulumi-resource-aws/schema.json  | sort -n | tail -5                                                                            
48
48
88
375
375
```

https://github.com/pulumi/pulumi-terraform-bridge/pull/781/ edits all the locations that are looping over PulumiToTerraformName.

Just a matter of time till someone attempts a provider with 1K props, but we can choose to leave this for later.

#### errors

Definitely for later. It feels that at least in some contexts PulumiToTerraformName should not be inventing Terraform names that don't exist on the fly. Catching this can be a chance to present a better error. But admittedly I'm not sure how to repro that situation or what the current error presentation is. In the PF version of the bridge if the SDK sends properties TF does not understand, it currently simply ignores them.

**Review by t0yv0 — APPROVED** [review]

**Comment by t0yv0** [comment]
Approving as it moves us forward significantly and fixes an important issue though I'm still not a fan of V2 function naming :)

**Comment by iwahbe** [comment]
> Approving as it moves us forward significantly and fixes an important issue though I'm still not a fan of V2 function naming :)

I think a clean set of exports is a 4.0 problem. We can fix the performance problem if it comes up by implementing a context cached but not exposing it.
