### PR TITLE
Check multiple docs locations

### LINKED ISSUE #1461: Docs are not picked up from `website` and `docs`
### What happened?

When trying to [upgrade pulumi-okta](https://github.com/pulumi/pulumi-okta/issues/414), we failed to pick up docs that TF displayed. These docs were in the upstream provider: `upstream/website/docs/r/app_oauth_role_assignment.html.markdown`, but were not picked up since we don't check `website/docs/r` since `docs/resources` also exists.

### Example

See :poin

### Output of `pulumi about`

NA

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #1461 and unblocks https://github.com/pulumi/pulumi-okta/issues/414.

### CODE REVIEW

File: pkg/tfgen/source.go [hunk 1]
```diff
@@ -193,23 +193,61 @@ func getMarkdownNames(packagePrefix, rawName string, globalInfo *tfbridge.DocRul
...
-		} else if !os.IsNotExist(err) && !errors.Is(err, &os.PathError{}) {
-			// Missing doc files are expected and OK.
-			//
-			// If the file we expect is actually a directory (PathError), that
-			// is also OK.
-			//
-			// Other errors (such as permission errors) indicate a problem
-			// with the host system, and should be reported.
-			return nil, fmt.Errorf("%s: %w", location, err)
+	for _, prefix := range locationPrefix {
```
Comment (iwahbe) [inline pkg/tfgen/source.go:201]: The only change within this loop is the extra layer of indentation.

**Review by t0yv0 — APPROVED** [review]
Very nice, long needed fixing!
