### PR TITLE
Fix azure loader issues

### LINKED ISSUE #1681: GitHub rate limit exceeded during tfgen
### What happened?

I was able to extract a stack trace via panic injection in the common library. Looks like the PCL->TypeScript phase of the conversion uses a plugin loader that misses the identity of the currently built provider and tries to locate "azurerm" in GitHub. 

```

panic: GitHub rate limit exceeded for https://api.github.com/repos/pulumi/pulumi-azurerm/releases/latest, try again in 15m33.818866s. You can set GITHUB_TOKEN to make an authenticated request with a higher rate limit.

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.(*githubSource).getHTTPResponse(0xc00f4adb60, 0xc003365ea0?, 0xc00ff64200)
        /Users/t0yv0/code/pulumi/sdk/go/common/workspace/plugins.go:430 +0x225
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.(*githubSource).GetLatestVersion(0xc00f4adb60, 0xc0102f8be0?)
        /Users/t0yv0/code/pulumi/sdk/go/common/workspace/plugins.go:445 +0x1c5
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.(*fallbackSource).GetLatestVersion(0xc00f4d8dc0, 0x7?)
        /Users/t0yv0/code/pulumi/sdk/go/common/workspace/plugins.go:597 +0x54
github.com/pulumi/pulumi/sdk/v3/go/common/workspace.PluginSpec.GetLatestVersion({{0xc0102f8be0, 0x7}, {0xabe18cb, 0x8}, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0})
        /Users/t0yv0/code/pulumi/sdk/go/common/workspace/plugins.go:918 +0x5b
github.com/pulumi/pulumi/pkg/v3/workspace.InstallPlugin({{0xc0102f8be0, 0x7}, {0xabe18cb, 0x8}, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0x0}, ...)
        /Users/t0yv0/code/pulumi/pkg/workspace/plugin.go:65 +0x78
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).loadSchemaBytes(0xc00548de40, {0xc0102f8be0, 0x7}, 0x0)
        /Users/t0yv0/code/pulumi/pkg/codegen/schema/loader.go:236 +0x1a5
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).LoadPackageReference(0xc00548de40, {0xc0102f8be0, 0x7}, 0x0)
        /Users/t0yv0/code/pulumi/pkg/codegen/schema/loader.go:151 +0x2df
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).LoadPackage(0x9a8ed80?, {0xc0102f8be0?, 0xc0102f8be0?}, 0x7?)
        /Users/t0yv0/code/pulumi/pkg/codegen/schema/loader.go:108 +0x18
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*loader).LoadPackage(0xc0054a4ca8, {0xc0102f8be0, 0x7}, 0x0)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/loaders.go:38 +0xbd
github.com/pulumi/pulumi/pkg/v3/codegen/schema.LoadPackageReference({0xb936420?, 0xc0054a4ca8?}, {0xc0102f8be0, 0x7}, 0x0)
        /Users/t0yv0/code/pulumi/pkg/codegen/schema/loader.go:194 +0xcc
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*PackageCache).loadPackageSchema(0xc002734000, {0xb936420, 0xc0054a4ca8}, {0xc0102f8be0, 0x7}, {0x0, 0x0})
        /Users/t0yv0/code/pulumi/pkg/codegen/pcl/binder_schema.go:163 +0x24b
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).loadReferencedPackageSchemas(0xc00f3f6880, {0xb99f1b8?, 0xc00645abb0?})
        /Users/t0yv0/code/pulumi/pkg/codegen/pcl/binder_schema.go:276 +0x32e
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.(*binder).declareNodes(0x95e2c60?, 0xc00f41b0c0)
        /Users/t0yv0/code/pulumi/pkg/codegen/pcl/binder.go:325 +0x2c5
github.com/pulumi/pulumi/pkg/v3/codegen/pcl.BindProgram({0xc00cd0cc98?, 0x1, 0x1}, {0xc00548de80, 0x6, 0x4?})
        /Users/t0yv0/code/pulumi/pkg/codegen/pcl/binder.go:210 +0xb05
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*cliConverter).convertPCL(0xc002d74b00, 0xc0034d0060?, {0xc00a99b000, 0x710}, {0xabe9b20, 0xa})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/convert_cli.go:401 +0x7ce
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*cliConverter).Convert(0xc002d74b00, {0xc0132ef000?, 0xc00ec2d5a8?}, {0xabe9b20, 0xa})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/convert_cli.go:187 +0x17e
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertHCLToString(0xc000005500, 0xc011c87458, {0xc0132ef000, 0x762}, {0xc0088f0680, 0x3f}, {0xabe9b20, 0xa})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/docs.go:1598 +0x2ed
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertHCL(0xc000005500, 0xc00f3fc500?, {0xc0132ef000, 0x762}, {0xc0088f0680, 0x3f}, {0x0, 0x0}, {0xc00f3e9b00, 0x6, ...})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/docs.go:1726 +0x2e5
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertExamplesInner(0xc000005500, {0xc006d1c000, 0x932}, {{0xc001844700?, 0x1?}, {0xc0088f0680?, 0x107baca?}}, 0x1, 0xc011c873f8, 0x1)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/docs.go:1415 +0xd23
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*cliConverter).FinishConvertingExamples.func1({0xc00d86c2a0?, 0x2?, 0x2?})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/convert_cli.go:158 +0x1c3
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*cliConverter).FinishConvertingExamples.(*Regexp).ReplaceAllFunc.func2({0xc0159a6000, 0x14e9006, 0x18a0000}, {0xc004e0e2c0?, 0xc0017f21e0?, 0x0?})
        /nix/store/brv7d6mlrclkzywf1vaf35wqhq4c0c82-go-1.21.5/share/go/src/regexp/regexp.go:707 +0x8c
regexp.(*Regexp).replaceAll(0xc0017f21e0, {0xc00d390000, 0x55be17, 0x55c000}, {0x0, 0x0}, 0x2, 0xc00ec2dfd8)
        /nix/store/brv7d6mlrclkzywf1vaf35wqhq4c0c82-go-1.21.5/share/go/src/regexp/regexp.go:642 +0x3e5
regexp.(*Regexp).ReplaceAllFunc(...)
        /nix/store/brv7d6mlrclkzywf1vaf35wqhq4c0c82-go-1.21.5/share/go/src/regexp/regexp.go:706
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*cliConverter).FinishConvertingExamples(_, {{0xc00100faa3, 0x5}, {0x0, 0x0}, {0xb949d40, 0x26}, {0xae6a0c0, 0x16b}, {0xc001946f40, ...}, ...})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/convert_cli.go:150 +0x21a
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).convertExamplesInSchema(_, {{0xc00100faa3, 0x5}, {0x0, 0x0}, {0xb949d40, 0x26}, {0xae6a0c0, 0x16b}, {0xc001946f40, ...}, ...})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/generate_schema.go:1022 +0xa1b
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).UnstableGenerateFromSchema(0xc000005500, 0xc00bc86280?)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/generate.go:952 +0x278
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0xc000005500)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/generate.go:909 +0x428
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main.func1({{0xabd7f79, 0x5}, {0xb949d40, 0x26}, {0x7ff7bfeff8d6, 0x6}, {{0xb9ac0a8, 0xc001946d40}, {0xabde11e, 0x7}, ...}, ...})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/main.go:48 +0x65
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x0?, {0xc0029560c0, 0x1, 0x0?})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/main.go:164 +0x635
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.RunFunc.func4(0x0?, {0xc0029560c0?, 0x0?, 0x0?})
        /Users/t0yv0/code/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x1c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.RunFunc.RunResultFunc.func6(0xc00050f200?, {0xc0029560c0, 0x1, 0x3})
        /Users/t0yv0/code/pulumi/sdk/go/common/util/cmdutil/exit.go:115 +0x38
github.com/spf13/cobra.(*Command).execute(0xc000005b00, {0xc00015e010, 0x3, 0x3})
        /Users/t0yv0/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005b00)
        /Users/t0yv0/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/t0yv0/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.MainWithCustomGenerate({_, _}, {_, _}, {{0xb9ac0a8, 0xc001946d40}, {0xabde11e, 0x7}, {0x0, 0x0}, ...}, ...)
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/main.go:61 +0x6f
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main({_, _}, {_, _}, {{0xb9ac0a8, 0xc001946d40}, {0xabde11e, 0x7}, {0x0, 0x0}, ...})
        /Users/t0yv0/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.73.1-0.20240206184959-b82e8b2a8aff/pkg/tfgen/main.go:40 +0x6e
main.main()
        /Users/t0yv0/code/pulumi-azure/provider/cmd/pulumi-tfgen-azure/main.go:25 +0xa7
make: *** [tfgen] Error 2
```

### Example

N/A

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #1681

For providers such as Azure Classic that have a discrepancy between "azure" and "azurerm", PULUMI_CONVERT=1 conversion no longer attempts to resolve and download the "azurerm" plugin from GitHub.

### CODE REVIEW

File: pkg/tfgen/convert_cli.go [hunk 1]
```diff
@@ -107,6 +110,12 @@ func (g *Generator) cliConverter() *cliConverter {
 		pluginHost:   g.pluginHost,
 		pcls:         map[string]translatedExample{},
 	}
+	if g.pluginHost != nil {
+		l := newLoader(g.pluginHost)
+		// Ensure azurerm resolves to azure for example:
+		l.aliasPackage(g.info.Name, string(g.pkg))
```
Comment (guineveresaenger) [inline pkg/tfgen/convert_cli.go:116]: nit: g.pkg has a `String()` method

**Review by guineveresaenger — APPROVED** [review]
I was trying to see if we could just call LoadPackage with the correct name but that looks to be not in scope of this repo. Oof.
I presume that the ProviderInfo.Name field _has_ to remain `azurerm` for pulumi-azure and that renaming that field instead would cause other issues?

Looks good to me, modulo thoughts and one minor nit.

**Comment by t0yv0** [comment]
LoadPackage is deep in the stack trace.. A good alternative behavior would be to fail fast when 'unknown_resource' is found in the example that doesn't belong to the known provider. But for now this works.
