### PR TITLE
Fix timeout handling when computing raw state delta

### LINKED ISSUE #3242: Pulumi raw state delta recovery failure when used from Any TF provider (dynamically bridged)
User @zlepper reported:

we are getting the same error when using a provider, that is generated via gen-sdk.
In this case I'm not even upgrading anything, but actually spinning up an entirely new instance of a service.

```
Diagnostics:
  pulumi:pulumi:Stack (rnd_digizuite/central_analytics/central_analytics_0dd72ece-5969-40a9-ac13-5de7b0d12394)
    error: update failed
 
  dgz:central-analytics:main$timescale:index/service:Service (central-timescale-postgresql)
    error: failed recovering value for turnaround check: Data integrity error: "__pulumi_raw_state_delta" does not apply cleanly to the resource state

If you are editing the state manually, try removing the "__pulumi_raw_state_delta" key and run Pulumi again.

If no manual state edits were involved, please report this as a bug

    https://github.com/pulumi/pulumi-terraform-bridge/issues

Detail: rawStateRecoverNatural cannot process Object values due to map vs object confusion
```
This provider has been generated by running:
```
pulumi package gen-sdk terraform-provider timescale/timescale --language dotnet --local
```

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #3242

### Description

We have seen an example of a TF provider `timescale/timescale` which when bridged dynamically via `terraform-provider` will generate resources that have a resource property input `timeouts` and output `timeouts`. 

[See full schema of bridged timescale/timescale@2.6.0](https://gist.github.com/Zaid-Ajaj/fd88ff74ff3040cde084eda6931ad5bd)

When trying to create a resource using timeouts as follows: 
```cs
var service = new Pulumi.Timescale.Service("my-timescale-service", new ()
{
    // Configure your Timescale service here
    Name = "my-timescale-service",
    MemoryGb = 2,
    MilliCpu = 500,
    RegionCode = "us-east-1",
    Timeouts = new ServiceTimeoutsArgs
    {
        Create = "15m",
    }
}, new CustomResourceOptions
{
    Provider = provider
});
```
The bridge will actually call `Create`, provision the resource successfully but then fail at the end when trying to compute the raw state delta. See full error in issue description but the most important part of the error is this:
```
Detail: rawStateRecoverNatural cannot process Object values due to map vs object confusion
```
This specific error happens because the bridge encountered `timeouts: { create: "5m" }` in the outputs but raw state delta information for it is _empty_: we handle `timeouts` in a special way and set their delta to empty. 

This PR changes the empty definition to a non-empty one but is NO-OP:
```diff
- RawStateDelta{}
+ RawStateDelta{Obj: &objDelta{PropertyDeltas: map[resource.PropertyKey]RawStateDelta{}}}
```
This solves the error coming from `rawStateRecoverNatural` but now when recovering the state, we do get raw state but it doesn't match up with original TF state because we remove `timeouts` before we compute the delta causing an issue:
```
recovered raw state does not byte-for-byte match the original raw state
```
This is handled by conditionally removing `timeouts` ONLY when they are not part of the data model of the terraform resource:
```go
var rawState rawstate.RawState
if _, hasTimeouts := outMap["timeouts"]; hasTimeouts {
	// if the outputs include timeouts, then they are part of the data model,
	// and we should not remove them so that raw state matches the outputs.
	rawState = newRawStateFromValue(schemaType, v)
} else {
	// otherwise, timeouts gets injected by terraform which we then remove from the raw state
	rawState = newRawStateFromValue(schemaType, v.Remove("timeouts"))
	if delta.Obj != nil {
		delete(delta.Obj.PropertyDeltas, "timeouts")
	}
}
```

Tested this locally against the `timescale` provider and confirmed that it works as expected 🎉 

~However, I cannot for whatever reason come up with a unit test that is capable of returning `timeouts` from  a terraform resource, they are always truncated. I've tried multiple version of the following test but they never include timeouts in their outputs. I don't know if this is an sdk-v2 / plugin-framwork difference or I could be missing something. cc @VenelinMartinov @corymhall~

EDIT: added test verifies the correctness of the implementation

<details>
<summary>Test that passes, specific to the plugin-framework</summary>

```go
// TestTimeoutsHandlingInResourceAttributes that shows using timeouts as part of the outputs works as indented
func TestTimeoutsHandlingInResourceAttributes(t *testing.T) {
	t.Parallel()
	provBuilder := pb.NewProvider(
		pb.NewProviderArgs{
			AllResources: []pb.Resource{
				pb.NewResource(pb.NewResourceArgs{
					CreateFunc: func(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
						timeoutsPath := path.Root("timeouts")
						resp.State.SetAttribute(ctx, timeoutsPath, map[string]any{
							"create": "30m",
						})
					},
					ResourceSchema: rschema.Schema{
						Attributes: map[string]rschema.Attribute{
							"timeouts": rschema.MapAttribute{
								Optional:    true,
								ElementType: types.StringType,
							},
						},
					},
				}),
			},
		})

	prov := provBuilder.ToProviderInfo()

	program := `
name: test
runtime: yaml
resources:
    mainRes:
        type: testprovider:index:Test
        properties:
            timeouts:
                create: "30m"
`

	pt, err := pulcheck.PulCheck(t, prov, program)
	require.NoError(t, err)

	pt.Up(t)
}
```
</details>

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
> I can help dig this up on Monday, there's a lot of workarounds that could use scrutiny if we are aiming to clean it up.

That would be great! This is definitely part of the system that is worth cleaning up and getting rid of special cases. For now though I suggest getting this in to unblock customers and revisit it as soon as possible. It is not the first time that we bubbled up internal errors about raw state delta to users which is supposed to be an implementation detail

File: pkg/pf/tests/schema_and_program_test.go [hunk 1]
```diff
@@ -74,6 +74,46 @@ resources:
...
+		})
+
+	prov := provBuilder.ToProviderInfo()
+
+	program := `
+name: test
+runtime: yaml
+resources:
+    mainRes:
+        type: testprovider:index:Test`
```
Comment (VenelinMartinov) [inline pkg/pf/tests/schema_and_program_test.go]: This doesn't match the snippet you added from the user - the user seems to be specifying the `timeouts` parameter on the resource - does that repro the issue in the test? In your test you have a fully computed property which can't be specified.

Comment (VenelinMartinov) [reply pkg/pf/tests/schema_and_program_test.go]: You might want something like this:

```golang
provBuilder := pb.NewProvider(
		pb.NewProviderArgs{
			AllResources: []pb.Resource{
				pb.NewResource(pb.NewResourceArgs{
					ResourceSchema: rschema.Schema{
						Attributes: map[string]rschema.Attribute{
							"timeouts": rschema.MapAttribute{
								Optional: true
								ElementType: types.StringType,
							},
						},
					},
				}),
			},
		})

```


and then:

```yaml
name: test
runtime: yaml
resources:
    mainRes:
        type: testprovider:index:Test
        properties:
            timeouts: "5min"
```

Comment (Zaid-Ajaj) [reply pkg/pf/tests/schema_and_program_test.go]: The problem is `timeouts` being part of the outputs, interacting with raw state delta special-handling it. Being part of the inputs doesn't matter here. The test running on `main` repro's the exact issue the customer is having.

Comment (Zaid-Ajaj) [reply pkg/pf/tests/schema_and_program_test.go]: @VenelinMartinov I've updated the test to your suggestion, can you have one more final look at the PR? 🙇 thank you!

**Comment by t0yv0** [comment]
> will generate resources that have a resource property input timeouts and output timeouts.

Sadness.

File: pkg/tfbridge/rawstate.go [hunk 2]
```diff
@@ -493,8 +493,20 @@ func RawStateComputeDelta(
 	pv := resource.NewObjectProperty(outMap)
 
 	delta := ih.delta(pv, v)
-	vWithoutTimeouts := v.Remove("timeouts")
-	err := delta.turnaroundCheck(ctx, newRawStateFromValue(schemaType, vWithoutTimeouts), pv)
+	var rawState rawstate.RawState
+	if _, hasTimeouts := outMap["timeouts"]; hasTimeouts {
```
Comment (t0yv0) [inline pkg/tfbridge/rawstate.go:497]: Nit: curious if we could use schema to check for "timeouts" being part of schema rather than guessing from the outMap? `schemaMap` is the "static" source of information.

File: pkg/tfbridge/rawstate.go [hunk 3]
```diff
@@ -493,8 +493,20 @@ func RawStateComputeDelta(
...
+		// if the outputs include timeouts, then they are part of the data model,
+		// and we should not remove them so that raw state matches the outputs.
+		rawState = newRawStateFromValue(schemaType, v)
+	} else {
+		// otherwise, timeouts gets injected by terraform which we then remove from the raw state
+		rawState = newRawStateFromValue(schemaType, v.Remove("timeouts"))
+		if delta.Obj != nil {
+			delete(delta.Obj.PropertyDeltas, "timeouts")
```
Comment (t0yv0) [inline pkg/tfbridge/rawstate.go:505]: This delete is new, any comment on an example where it's needed, curious?

Comment (Zaid-Ajaj) [reply pkg/tfbridge/rawstate.go:505]: We remove `timeouts` from `v` after the delta has been computed so the delta will contain a field for `timeouts`.  Here I am removing that field from the delta as well. I think it might be redundant now after I changed the shape of the delta to be no-op but before it was causing a problem as folllows:
 - `outMap` (pulumi) doesn't contain `timeouts` 
 - delta in state tries to recover `timeouts` data because the field  exists in the delta
 - recovery fails with `rawStateRecoverNatural cannot process Object values due to map vs object confusion`
 - code path for `rawStateRecoverNatural` activated because there was an empty delta but no corresponding value

**Comment by Zaid-Ajaj** [comment]
> SDKv2 might have the same issue but @Zaid-Ajaj you're probably have the freshest context on whether it's fixed here or not. If it's not fixed let's backlog it - this is a fairly rare situation.

I simply could not repro this specific state delta issue in sdkv2 because from what I've tested, `timeouts` property is always _truncated_. See the following test that has computed `timeouts`, populated by the provider but doesn't show up in resource outputs:

<details>
<summary>Test with timeouts as outputs</summary>

```go
func TestTimeoutsHandlingAsResourceProperty(t *testing.T) {
	t.Parallel()

	res := &schema.Resource{
		Timeouts: &schema.ResourceTimeout{
			Create: schema.DefaultTimeout(time.Second * 10),
		},
		CreateContext: func(ctx context.Context, rd *schema.ResourceData, _ interface{}) diag.Diagnostics {
			rd.SetId("irrelevant")
			rd.Set("timeouts", map[string]string{
				"create": "5m",
			})
			return nil
		},
		Schema: map[string]*schema.Schema{
			"test": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"timeouts": {
				Type:     schema.TypeMap,
				Elem:     schema.TypeString,
				Computed: true,
			},
		},
	}

	tfp := &schema.Provider{
		ResourcesMap: map[string]*schema.Resource{
			"prov_test": res,
		},
	}

	bridgedProvider := pulcheck.BridgedProvider(t, "prov", tfp)

	pt := pulcheck.PulCheck(t, bridgedProvider, `
        name: test
        runtime: yaml
        resources:
            mainRes:
                type: prov:index:Test
                properties:
                    test: hello
        outputs:
            result: ${mainRes.timeouts}`)

	upResult := pt.Up(t)
	result, ok := upResult.Outputs["result"]
	require.True(t, ok, "expected output 'result' to be present")
    ///// result.Value === nil 
}
```

</details>

So I believe it is a different issue than what's happening in raw state delta handling with the timeouts. 

I am going to open another issue with it anyways but will go ahead and merge this one
