### PR TITLE
Fix #1381

### LINKED ISSUE #1381: PreCheckCallback cannot modify inputs for Plugin Framework
### What happened?

Looks like due to a simple omission, PreCheckCallback is not allowed to modify inputs for Plugin Framework resources, like it does for normal resources. This functionality is relied on, among other things, for default tags application in pulumi-aws and is not working as expected for PF resources.

### Example

N/A

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #1381  - with this change PreCheckCallback starts working the same way for Plugin Framework resources as normal resources, that is it can return a modify inputs map to be used in place of the original map. This arose in the context of investigating tags secrets leaks for pulumi-aws and in particular how tags/tagsAll behavior is different between normal and PF based resources in the currently released version.

### CODE REVIEW

File: pf/tfbridge/provider_check.go [hunk 1]
```diff
@@ -48,7 +48,8 @@ func (p *provider) CheckWithContext(
 
 	if info := rh.pulumiResourceInfo; info != nil {
 		if check := info.PreCheckCallback; check != nil {
-			checkedInputs, err := check(ctx, checkedInputs, p.lastKnownProviderConfig.Copy())
+			var err error
+			checkedInputs, err = check(ctx, checkedInputs, p.lastKnownProviderConfig.Copy())
```
Comment (t0yv0) [inline pf/tfbridge/provider_check.go:52]: Shadowing considerer harmful.. it got me here again.

Comment (iwahbe) [reply pf/tfbridge/provider_check.go:52]: I think the pain point is that the difference between a declaration and a mutation is `:`. It somehow bothers me less then its `let ` or `auto ` or `(let ((`.

**Review by iwahbe — APPROVED** [review]
