### PR TITLE
Correctly mux aliases

### LINKED ISSUE #1016: Muxer does not map aliased resources
### What happened?

When computing the mapping for a muxed (hybrid) pf & sdk provider, we don't attribute resources that are aliases back to their originating provider.

### Expected Behavior

Aliasing as called via bridge methods should _just work_™️. If something won't work, it should error during `make tfgen` so it doesn't become end user facing.

### Steps to reproduce

Attempt to serve a hybrid provider with an alias. For example, in pulumi-aws there is code that renames the alb resource with alias:

```

	prov.RenameResourceWithAlias("aws_alb", awsResource(legacyAlbMod, "LoadBalancer"),
		awsResource(albMod, "LoadBalancer"), legacyAlbMod, albMod, &tfbridge.ResourceInfo{
			Fields: map[string]*tfbridge.SchemaInfo{
				"load_balancer_type": {Type: awsResource(albMod, "LoadBalancerType")},
				"ip_address_type":    {Type: awsResource(albMod, "IpAddressType")},
			},
			Docs: &tfbridge.DocInfo{Source: "lb.html.markdown"},
		})

```

When using a muxed build of pulumi-aws, schema generation proceeds fine but tests fail with:

```
Resource type 'aws:elasticloadbalancingv2/loadBalancer:LoadBalancer' not found.
```

The error comes from a missing entry in the DispatchTable for this resource.

### Output of `pulumi about`

NA

### Additional context

On bridge version v3.44.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #1016

### CODE REVIEW

File: pf/internal/muxer/muxer.go [hunk 1]
```diff
@@ -119,31 +121,88 @@ func newProviderShim(provider shim.Provider) ProviderShim {
...
+}
+
+// Resolve either resources or datasoruces into their originating providers.
+//
+// A resource/datasource is considered "from" a provider if the provider serves a
+// resource/datasource for the token or if the provider serves a resource that matches the
+// resource inserted into the global map of m. The latter logic is used to handle aliases
+// which are inserted via:
+//
+//	p.P.ResourcesMap().Set(legacyResourceName, p.P.ResourcesMap().Get(resourceName))
```
Comment (iwahbe) [inline pf/internal/muxer/muxer.go:160]: This is the explanation for how we are recovering information.

File: pf/internal/muxer/muxer.go [hunk 2]
```diff
@@ -119,31 +121,88 @@ func newProviderShim(provider shim.Provider) ProviderShim {
...
+func resolveDispatchMap[T interface{ GetTok() tokens.Token }](
```
Comment (iwahbe) [inline pf/internal/muxer/muxer.go:161]: Cool trick: `type Foo interface { Bar() }` is really just saying `Foo` is a type that resolves to `interface { Bar() }`. Whenever you need to supply a type in Go, you can provider either a type name (`Foo`) or a type value `interface { Bar() }`. Even in generics.

**Review by t0yv0 — APPROVED** [review]

**Comment by t0yv0** [comment]
Thank you or this 🚢
