### PR TITLE
Do not skip default attribute of variables when explicitly set to null

### LINKED ISSUE #1055: Converting `terraform-aws-github-runner`: error `missing required attribute 'environment'`
Error converting https://github.com/philips-labs/terraform-aws-github-runner

```
$ pulumi convert --from terraform --language typescript --out pulumi
warning: Plugin converters are currently experimental
error: could not generate output program: load pcl program: main.pp:98,1-103,2: missing required attribute 'environment'; missing required attribute 'environment', and 3 other diagnostic(s)
```

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #1055 

Blocked by https://github.com/pulumi/pulumi/pull/12817 as we need the new bind logic from this PR for the tests here to succeed

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Updated references to pulumi/pulumi to latest and no longer blocked by https://github.com/pulumi/pulumi/pull/12817 cc @Frassle

File: pkg/tf2pulumi/convert/tf.go [hunk 1]
```diff
@@ -1516,6 +1516,16 @@ func convertVariable(sources map[string][]byte, scopes *scopes,
 		modifiedDefault := camelCaseObjectAttributes(variable.Default)
 		blockBody.SetAttributeValue("default", modifiedDefault)
 	}
+
+	if variable.Default.IsNull() && variable.Default.Type() != cty.NilType {
```
Comment (Frassle) [inline pkg/tf2pulumi/convert/tf.go:1520]: Can't this just change the condition above? Instead of `if !variable.Default.IsNull()` have `variable.Default.Type() != cty.NilType`. At the very least make this an else if:
```
if !variable.Default.IsNull() {
...
} else if variable.Default.Type() != cty.NilType {
  blockBody.SetAttributeValue("default", cty.NilVal)
}

File: pkg/tf2pulumi/convert/testdata/simple_config/main.tf [hunk 2]
```diff
@@ -7,6 +7,11 @@ variable "string_in" {
     type = string
 }
 
+variable "nullable_string_in" {
```
Comment (Frassle) [inline pkg/tf2pulumi/convert/testdata/simple_config/main.tf:10]: What do with:
```
variable "opt_in" {
  default = null
}
```

File: pkg/tf2pulumi/convert/testdata/simple_config/main.tf [hunk 3]
```diff
@@ -12,6 +12,10 @@ variable "nullable_string_in" {
     default = null
 }
 
+variable "opt_in" {
```
Comment (Frassle) [inline pkg/tf2pulumi/convert/testdata/simple_config/main.tf:15]: I'd probably call it `opt_any_in`

File: pkg/tf2pulumi/convert/tf.go [hunk 4]
```diff
@@ -1515,9 +1515,7 @@ func convertVariable(sources map[string][]byte, scopes *scopes,
 		// i.e. { first_key = "hello" } becomes { firstKey = "hello" }
 		modifiedDefault := camelCaseObjectAttributes(variable.Default)
 		blockBody.SetAttributeValue("default", modifiedDefault)
-	}
-
-	if variable.Default.IsNull() && variable.Default.Type() != cty.NilType {
+	} else if variable.Default.IsNull() && variable.Default.Type() != cty.NilType {
```
Comment (Frassle) [inline pkg/tf2pulumi/convert/tf.go:1518]:
```suggestion
	} else if variable.Default.Type() != cty.NilType {
```

Comment (Zaid-Ajaj) [reply pkg/tf2pulumi/convert/tf.go]: Done ✅

File: pkg/tf2pulumi/convert/testdata/simple_config/main.tf (hunk 3 above)
Comment (Zaid-Ajaj) [reply pkg/tf2pulumi/convert/testdata/simple_config/main.tf]: Done ✅

**Review by Frassle — APPROVED** [review]
