### PR TITLE
Correct .P == nil error message

### LINKED ISSUE #1309: Out of date warning for bridged providers
### What happened?

When bridging a PF based provider, a user hit this warning:

https://github.com/pulumi/pulumi-terraform-bridge/blob/beb85b03de3e2b1a7c43957486e302fbb49d56fe/pf/tfgen/not_supported.go#L54-L57

We warn on a condition that is now correct (and required), since https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/pf%2Fv0.12.0.

### Expected Behavior

Warnings are correct and actionable.

### Steps to reproduce

Bridge a PF provider. I believe that this code not runs on all valid bridged PF providers.

### Output of `pulumi about`

NA

### Additional context

This issue was opened because of a discussion in community slack: https://pulumi-community.slack.com/archives/C04NPQTRKM4/p1690390786534849.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #1309

### CODE REVIEW

File: pkg/tfbridge/schema.go [hunk 1]
```diff
@@ -1102,13 +1102,15 @@ func MakeTerraformState(res Resource, id string, m resource.PropertyMap) (shim.I
 			return nil, err
 		}
 	} else if res.TF.SchemaVersion() > 0 {
-		// If there was no metadata in the inputs and this resource has a non-zero schema version, return a meta bag
-		// with the current schema version. This helps avoid migration issues.
+		// If there was no metadata in the inputs and this resource has a non-zero
```
Comment (t0yv0) [inline pkg/tfbridge/schema.go:1105]: We need to agree on fill-column-width setting in Emacs.

**Review by t0yv0 — APPROVED** [review]
Nice fix, thank you!
