### PR TITLE
Complete set of numeric types in MakeTerraformOutput

### LINKED ISSUE #1441: Incomplete set of numeric types handled in MakeTerraformOutput leading to a panic
### What happened?

```
// Create a new Exoscale cluster
const cluster = new exo.SKSCluster("cluster", {
    zone: config.get("zone") ?? "at-vie-1",
    cni: "calico",
    version: config.get("kubernetesVersion") ?? "1.28.2",
});

// Create a new node pool
const nodePool = new exo.SKSNodepool("nodepool", {
    clusterId: cluster.id,
    zone: config.get("zone") ?? "at-vie-1",
    instanceType: config.get("nodePoolType") ?? "standard.medium",
    size: config.getNumber("nodePoolSize") ?? 1,
});
```

```
   panic: fatal: A failure has occurred: Unexpected TF output property value: 50
    goroutine 116 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.86.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x102f719ff?, 0x1032ce1e0?}, {0x14000540fe8?, 0x1035cabf0?, 0x10358dae0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.86.0/go/common/util/contract/fail.go:32 +0xbc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0x1035f5ca0, 0x1400003aec0}, {0x1032ce1e0, 0x1031b80a0}, {0x1035f7fa0, 0x1400061b2c0}, 0x0, 0x1400035eba0, 0x0, 0x2?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.61.0/pkg/tfbridge/schema.go:1080 +0x450
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0x1035f5ca0?, 0x1400003aec0?}, {0x1032ce1e0?, 0x1031b80a0?}, {0x1035f7fa0?, 0x1400061b2c0?}, 0x14000541268?, 0x483c?, 0xc8?, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.61.0/pkg/tfbridge/schema.go:1085 +0x4c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0x1035f5ca0, 0x1400003aec0}, 0x8e?, {0x1035e81e8, 0x14000213f20}, 0x1026c6634?, 0x1035e81e8?, 0x20?, 0x3f?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.61.0/pkg/tfbridge/schema.go:958 +0x124
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Check(0x140004bcb00, {0x1035e24e8?, 0x1400035e7b0?}, 0x14000812660)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.61.0/pkg/tfbridge/provider.go:607 +0x7f4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Check.func1({0x1035f6ff8?, 0x140004bcb00?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:332 +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x14000185130?, 0x140001fb778, 0x140001fb758?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:303 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Check(0x140001fb7b8?, {0x1035e24e8?, 0x1400035e7b0?}, 0x1032d97c0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.6/muxer.go:331 +0x5c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x1035e24e8, 0x1400035e7b0}, {0x1034c6ea0?, 0x14000812660})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.86.0/proto/go/provider_grpc.pb.go:557 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1035e24e8, 0x1400035e6c0}, {0x1034c6ea0, 0x14000812660}, 0x14000452e40, 0x14000808ba0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x308
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x10356d600?, 0x14000185130}, {0x1035e24e8, 0x1400035e6c0}, 0x140003750a0, 0x14000636020)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.86.0/proto/go/provider_grpc.pb.go:559 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400041e000, {0x1035eea80, 0x140009024e0}, 0x14000682240, 0x14000805a70, 0x1041350f0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
    google.golang.org/grpc.(*Server).handleStream(0x1400041e000, {0x1035eea80, 0x140009024e0}, 0x14000682240, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x16c
```

### Example

N/A

### Output of `pulumi about`

N/A

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by VenelinMartinov**
This should fix #1441.

We were not correctly handling all terraform output types, missing out on int8, int16 etc...

The regression test added with this PR reproduced the issue.

### CODE REVIEW

File: pkg/tfbridge/schema.go [hunk 1]
```diff
@@ -1006,9 +1006,9 @@ func MakeTerraformOutput(p shim.Provider, v interface{},
 		switch val.Kind() {
 		case reflect.Bool:
 			return resource.NewBoolProperty(val.Bool())
-		case reflect.Int:
+		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
 			return resource.NewNumberProperty(float64(val.Int()))
```
Comment (t0yv0) [inline pkg/tfbridge/schema.go:1010]: // Int returns v's underlying value, as an int64.
// It panics if v's Kind is not Int, Int8, Int16, Int32, or Int64.
func (v Value) Int() int64 {

This sounds good, it's th largest of them.

**Review by t0yv0 — APPROVED** [review]
Let's merge this. @dirien we still need help with a proper repro if possible! We could not find creds to test exoscale provider.  Just in case it's actually Big Int or some such structure.

**Comment by t0yv0** [comment]
While editing this code, could we improve  the error message here:

```
contract.Failf("Unexpected TF output property value: %#v", v)
```

It would be useful to know the type of the value v, I think `%#T` or some such specifier prints out the type.
