### PR TITLE
Fix no longer being able to place types in top-level modules #1300

### LINKED ISSUE #1300: No longer able to place types in top-level modules
### What happened?

There appears to be a regression in the ability to place types in external modules.

To reproduce, assign a following token to a resource:

```
		Resources: map[string]*tfbridge.ResourceInfo{
			"myprovider_myresource": {
				Tok: "myprovider:mymodule:MyResource",
			},
		},
```

This is not a typical token allocation strategy as most Pulumi providers use  "myprovider:myparentmodule/mymodule:MyResource", however it is used in the wild and the ability to do this has regressed, causing upgrade issues.

Current behavior during `make tfgen`:

```
panic: fatal: An assertion has failed: QName "myModule" has invalid namespace ""

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x0?, {0x1023fd4f4?, 0x1028ec168?}, {0x140008bb2e8?, 0x1400030ba20?, 0x15?})
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/go/common/util/contract/assert.go:35 +0xe0
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.QName.Namespace({0x1400030ba2b, 0xa})
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/go/common/tokens/names.go:117 +0x110
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.parentModuleName(...)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:1041
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.parentModule({0x1400030ba20, 0x15})
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:1036 +0x3c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.parentModuleOrDefault(...)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:1026
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.modulePlacementForType({0x14000a8af50, 0xa}, {0x102f124f0, 0x1400097d3b0})
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:1011 +0x1fc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.modulePlacementForTypeSet({0x14000a8af50, 0xa}, 0x14000304c40?)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:971 +0x11c
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*schemaGenerator).genObjectTypeToken(0x140008bd8f8, 0x14000465480)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:650 +0x94
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*schemaGenerator).genPackageSpec(_, _)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:244 +0x1d78
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.genPulumiSchema(_, {_, _}, {_, _}, {{0x102f26300, 0x14000a9c380}, {0x1023c144a, 0xa}, {0x0, ...}, ...}, ...)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate_schema.go:209 +0xbc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.(*Generator).Generate(0x14000788900)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/generate.go:856 +0xdc
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main.func1({{0x1023c144a, 0xa}, {0x1028ec180, 0x9}, {0x16f0ef8eb, 0x6}, {{0x102f26300, 0x14000a9c380}, {0x1023c144a, 0xa}, ...}, ...})
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/main.go:44 +0x50
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.newTFGenCmd.func1(0x0?, {0x14000a45110, 0x1, 0x0?})
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/main.go:162 +0x498
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0x0?, {0x14000a45110?, 0x0?, 0x0?})
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/go/common/util/cmdutil/exit.go:96 +0x28
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0x14000788300?, {0x14000a45110, 0x1, 0x3})
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.75.0/go/common/util/cmdutil/exit.go:112 +0x38
github.com/spf13/cobra.(*Command).execute(0x14000788300, {0x1400004c090, 0x3, 0x3})
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x14000788300)
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/anton.tayanovskyy/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.MainWithCustomGenerate({_, _}, {_, _}, {{0x102f26300, 0x14000a9c380}, {0x1023c144a, 0xa}, {0x0, 0x0}, ...}, ...)
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/main.go:57 +0x54
github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfgen.Main({_, _}, {_, _}, {{0x102f26300, 0x14000a9c380}, {0x1023c144a, 0xa}, {0x0, 0x0}, ...})
        /Users/anton.tayanovskyy/code/pulumi-terraform-bridge/pkg/tfgen/main.go:36 +0x58

```

### Expected Behavior

"myprovider:mymodule:MyResource" works as before.

### Steps to reproduce

make tfgen on top of

```
Resources: map[string]*tfbridge.ResourceInfo{
			"myprovider_myresource": {
				Tok: "myprovider:mymodule:MyResource",
			},
		},
```

### Output of `pulumi about`

N/A

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #1300 

This restores the ability to place resources into top-level modules by making tokens like "myprovider:mymodule:MyResource", something that accidentally regressed and was not caught as most Pulumi-managed providers opt for a submodule scheme like "myprovider:mymodule/mysubmodule:MyResource", and the code started to accidentally assume this scheme.

### CODE REVIEW

File: pkg/tfgen/generate_schema.go [hunk 1]
```diff
@@ -1018,8 +1019,18 @@ func modulePlacementForType(pkg tokens.Package, path paths.TypePath) tokens.Modu
 	}
 }
 
-func parentModule(m tokens.Module) tokens.Module {
-	return tokens.NewModuleToken(m.Package(), parentModuleName(m.Name()))
+func parentModuleOrDefault(m tokens.Module, def tokens.Module) tokens.Module {
```
Comment (thomas11) [inline pkg/tfgen/generate_schema.go:1022]: This func only seems to be called with two identical args? And the `m` arg is always overwritten? Can this be cleaned up?

Comment (t0yv0) [reply pkg/tfgen/generate_schema.go:1022]: Ah sure. Yes happy to clean this up.

Comment (t0yv0) [reply pkg/tfgen/generate_schema.go]: Done

**Review by thomas11 — APPROVED** [review]
